# Generated by Django 3.0.5 on 2020-11-16 09:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('uname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('pic', models.FileField(blank=True, default='pic/default.png', null=True, upload_to=accounts.models.user_directory_path)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
