# Generated by Django 3.0.5 on 2020-11-17 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=225)),
                ('des', models.CharField(max_length=225)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('postfile', models.FileField(upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post_views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Signup')),
            ],
            options={
                'db_table': 'health_data',
            },
        ),
    ]
