# Generated by Django 3.0.5 on 2020-11-16 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
