# Generated by Django 3.0.5 on 2020-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0002_health_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_data',
            name='post_views',
            field=models.IntegerField(default=0),
        ),
    ]
